### ISSUE TITLE
package is not supporting in lazy loaded module is 

### ISSUE THREAD

**Issue by sedhurabe** [MuminCelal/ngx-org-ui#33]
ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by MuminCelal** [comment]
Hi @sedhurabe,

Thank you. I will look at it.

**Comment by SuryaP1987** [comment]
@MuminCelal, if we use **import { CommonModule } from '@angular/common';** instead of **import { BrowserModule } from '@angular/platform-browser';** this lazy loading issue would be resolved. I made the code changes in my local but I am unable to create pull request.

**Comment by MuminCelal** [comment]
Thank you @SuryaP1987.

**Comment by SuryaP1987** [comment]
> Thank you @SuryaP1987.

Thanks for merging the code @MuminCelal. May I know when this change can be published to npmjs? Eagerly waiting this to be available soon.

**Comment by MuminCelal** [comment]
> > Thank you @SuryaP1987.
> 
> Thanks for merging the code @MuminCelal. May I know when this change can be published to npmjs? Eagerly waiting this to be available soon.

@SuryaP1987 I published library to npmjs.

**Comment by SuryaP1987** [comment]
> > > Thank you @SuryaP1987.
> > 
> > 
> > Thanks for merging the code @MuminCelal. May I know when this change can be published to npmjs? Eagerly waiting this to be available soon.
> 
> @SuryaP1987 I published library to npmjs.

yes.. Now we able to load the org chart component lazily. Thanks for quick turnaround.
